# Generated by Django 4.2 on 2023-04-08 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=10)),
                ('surname', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.EmailField(max_length=254)),
                ('date_publication', models.DateField(max_length=10)),
                ('publication', models.CharField(max_length=10)),
                ('price_publication', models.IntegerField()),
                ('publication_sell', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.EmailField(max_length=254)),
                ('date_purchase', models.DateField(max_length=10)),
                ('purchase', models.CharField(max_length=10)),
                ('price_purchase', models.IntegerField()),
            ],
        ),
    ]
