# Generated by Django 4.2 on 2023-04-10 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_alter_publications_publication_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clients',
            new_name='Users',
        ),
    ]
