# Generated by Django 4.2 on 2023-04-22 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0005_remove_project_created_by_remove_project_assigned_to_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='assigned_to',
            new_name='project_leader',
        ),
    ]
